import { Geist, Geist_Mono } from "next/font/google";
import ColorBends from "../components/ColorBends";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "indu brolk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <div className="relative min-h-screen">
          
          
        <div className="relative z-10">{children}</div>
        </div>
        
      </body>
    </html>
  );
}
